---
title: " "
format: html
---

# Papers

Lee, S., & Kim, S. (2026). Comparing Bayesian random coefficient prediction and latent interaction models for multilevel moderated mediation. Frontiers in Psychology: Quantitative Psychology and Measurement, 16: 1543330.

Kim, S. (2025). The mediating role of changes in academic self-concept between growth mindset and academic achievement. Korean Educational Research Journal, 46(2), 61-85.

Ryu, H., & Kim, S. (2025). Classification of changes in academic performance in early adolescence and associated predictors: The COVID-19 pandemic as a turning point. The Korea educational review, 31(2), 47-68.

Kim, H., Ryu, H., & Kim, S. (2025). Classifying latent profiles in emotion recognition ability of youth and parents: Verifying the effects of relevant factors. Studies on Korean Youth, 36(1), 115-136.

Chung, Y., & Kim, S. (2024). Longitudinal changes in discrepancies between adolescents’ and parents’ academic and emotional support and their relationships to changes in academic self-concept and intrinsic motivation. Korean Journal of Educational Psychology, 38(4), 335-356.

Lee, J., & Kim, S. (2023). Longitudinal changes in the career development of early adolescents and the influences of individual, parental, and peer factors. Korean Educational Research Journal, 44(3), 287-312.

Chung, Y., & Kim, S. (2022). Expectancies, task values, and perceived costs: Reciprocal effects on math-related career intention and achievement among middle school girls, Learning and Individual Differences, 96, 102145. DOI: 10.1016/j.lindif.2022.102145

Kim, S., Jeong, Y., & Hong, S. (2021). The impact of ignoring a crossed factor in cross-classified multilevel modeling. Frontiers in Psychology: Quantitative Psychology and Measurement, 12, 637645. DOI:10.3389/fpsyg.2021.637645

Chung, Y., Kim, S., & Song, J. (2020). Exploring antecedents of achievement goal profiles in elementary school and their relationship to academic aAdaptation. Korean Journal of Educational Psychology, 34(2), 369-392.

Kim, S., & Hong, S. (2020). Comparing Methods for multilevel moderated mediation: A Decomposed-first strategy. Sructural Equation Modeling: A Multidisciplinary Journal, 27(5), 661-677. DOI: 10.1080/10705511.2019.1683015

Kim, S., & Song, J. (2020). Latent transition analysis between the latent profiles of parenting styles and the growth latent classes of adolescents' task values. Studies on Korean Youth, 31(2), 123-154.

Kim, S., & Hong, S. (2019). The Effects of the Profiles of Foreign Parents’ Cultural Adaptation on the Classes in the Growth of Multicultural Adolescents’ Cultural Adaptation Stress: Applying Latent Transition Analysis. Survey Research, 19(4), 35–74.

Hong, S., & Kim, S. (2019). Comparisons of multilevel modeling and structural equation modeling approaches to actor–partner interdependence model. Psychological Reports. DOI: 10.1177/0033294118766608

Kim, S., & Hong, S. (2018). The effects of school contexts and student characteristics on cognitive and affective achievement in South Korea. Asia Pacific Educational Research, 19(4), 557–572. DOI: 10.1007/s12564-018-9557-2

Kim, S., Nam, Y., & Hong, S. (2018). Casual effects of youth employment policies on the latent classes of job satisfaction. Survey Research, 19(4), 35–74.

Kim, S., Jang, Y., & Hong, S. (2016). The causal effects of latent classes of job preparation efforts on employment outcomes: Focusing on the wages and the job satisfaction. Survey Research, 17(4), 1–33.

Kim, S., & Hong, S. (2015). Longitudinal changes in infants emotional temperament: effects of maternal psychological characteristics and infant's gender. Korean Journal of Infant Education, 35(4), 301–317.

Kim, S., & Hong, S. (2014). Estimating adolescent’s changes in mobile phone dependence: Testing for the effects of ecological factors on individual differences in the changes. Studies on Korean Youth, 25(3), 101–123.

Kim, S., & Hong, S. (2013). Identifying latent profile in vacation preparation behaviors of vocational high school students and testing its relationship with vocational education. Survey Research, 14(1), 93–116.

Kim, S., & Hong, S. (2012). Identifying and predicting trajectories of latent class in adolescents’ suicidal ideation. Studies on Korean Youth, 23(1), 251–275.  
  
  
# Presentations

Ryu, H., & Kim, S. (2025). Comparison of RDSEM approaches in continuous-time and discrete-time. International Meeting of the Psychometric Society. Minneapolis, MN, US.

Kim, S. (2025). Cross-classified Mediation Model with a Between-person Predictor. International Meeting of the Psychometric Society. Minneapolis, MN, US.

Chung, Y., Song. J., & Kim, S. (2020). Changes of achievement goal profiles across school transitions: Antecedents and consequences. European Congress of Methodology (Virtual phase)

Kim, S. (2020). The effects of modeling without a crossed-factor in the cross-classified random effect model. European Congress of Methodology (Virtual phase)

Kim, S. (2019). Latent transition between the profiles of parenting styles and the growth classes of task values. Korean Children and Youth Panel Survey Conference. Seoul, Korea.

Kim, S., & Hong, S. (2019). Comparing the decompose–first strategies in the 2–1–1 multilevel mediation with a moderator. American Educational Research Association. Toronto, Canada.

Cho, S., & Kim, S. (2019). Trajectories of academic burnout in secondary to postsecondary transitions: Role of social support. American Educational Research Association. Toronto, Canada.

Kim, S., Jang, Y, & Hong, S. (2017). The single indicator method in multilevel structural equation modeling. International Meeting of the Psychometric Society. Zürich, Switzerland.

No, U., Kim, S., & Hong, S. (2017). Applying competing risk discrete-time event history analysis to testing the determinants on the onset of adolescents' status delinquency. International Convention of Psychological Science, Vienna, Austria.

Kim, S., Jang, y., & Hong, S. (2016). The causal effects of latent classes of job preparation efforts on employment outcomes: Focusing on the wages and the job satisfaction. Korean Psychological Association: Measurement and Evaluation. Seoul, Korea.

Kim, S., Lee, S., & Hong, S. (2016). Relational analysis of internal schooling and achievement to evaluate school effectiveness. American Educational Research Association. Washington D.C. US.

Kim, S. (2015). Effects of school context factors about cognitive/affective achievement. Paper presented at the annual meeting of the National Assessment of Educational Achievement Data Analysis Symposium. Seoul, Korea.

Kim, S., & Hong, S. (2015). A latent transition analysis of the computer usage of adolescents: Longitudinal transition and testing the effect of predictors. European Conference on Psychological Assessment. Zürich, Switzerland.

Kim, S., & Hong, S. (2015). Longitudinal changes in infants’ difficult temperament: The effects of gender and maternal psychological characteristics. European Conference on Psychological Assessment. Zürich, Switzerland.

Kim, S., & Hong, S. (2015). Rasch rating scale modeling of the sociopolitical control scale. Poster presented at the biannual meeting of the European Conference on Psychological Assessment. Zürich, Switzerland.

Kim, S., & Lee, S. (2015). Mediation effects in the relationship between the marital satisfaction and the marital conflict applying dyadic latent growth modeling. Korean Psychological Association: Measurement and Evaluation. Seoul, Korea.

Kim, S., & Hong, S. (2015). Study of structural equation modeling approach and hierarchical linear modeling approach to Actor–Partner Interdependence Model. Korean Psychological Association: Measurement and Evaluation. Seoul, Korea.

Kim, S., & Hong, S. (2014). Developing a short form of the Personal Style Inventory–II using the Rasch model. Poster presented at the annual meeting of the American Educational Research Association. Philadelphia, P.A, US.

Kim, S. (2013). Estimating adolescent’s changes in cell phone addiction: test of the effects of ecological variables on individual differences in the changes. Korean Children and Youth Panel Survey Conference. Seoul, Korea.
