---
title: ""
format: html
---

# About QAMP Lab

> QAMP에서는 인간행동이나 심리적 속성에 대한 수량화 및 모델링, 기존의 분석 방법을 확장하거나 방향을 제시하는 연구, 양적자료 분석에 있어서 새로운 방법을 제안하거나 평가하는 연구를 수행합니다. 행동과학이라는 독특한 맥락 내에서 생긴 방법론에 대하여 탐구하는데 초점이 맞추어져 있습니다. '심리학'이라고 생각하기 보다는 '응용 통계'라고 생각하는 것이 이해가 더 빠를 수 있습니다. 

> QAMP에서 수행하는 연구의 목표는 크게 다음의 세 가지 정도로 나눌 수 있습니다.\
> (1) 심리학 연구에 적용되는 연구 설계나 분석에서 어떠한 문제점이 나타날 수 있으며 어떻게 해결할 수 있는지 소개하고 더 나은 방향을 제시. 기존의 분석 방법들을 실제 분석상황에서 나타나는 다양한 조건에서 평가\
> (2) 척도의 타당도와 신뢰도를 평가하고, 측정학적으로 더 나은 척도 연구 및 개발\
> (3) 새로운 양적분석 방법을 행동과학 분야에 적용하여 기존의 방법론으로는 알 수 없었던 함의점 도출

\


* 대학원 진학에 관심이 있는 분은 지원 전에 면담을 하는 것이 좋겠습니다. 면담은 교수님께 이메일을 보내 시간 약속을 정하시기를 권장합니다.

\
\
\

# FAQ


#### 1 . 대학원 진학 전에 무엇을 준비하면 좋을까요?

> 심리측정통계를 전공하기 위해 갖추어야 할 점을 중요도 순으로 나열하면 (1) 전공에 대한 흥미, (2) 논리적 사고, (3) 언어•의사소통 능력, (4) 기초 컴퓨터 언어입니다.\
심리통계나 양적연구방법론에 대한 흥미와 호기심은 전공 분야를 깊이 있게 파고들기 위해 필수적입니다. 심리통계나 방법론을 수강하면서 통계분석이 유용하다고 느꼈고 더 알고싶다는 생각이 들었다면 절반은 준비가 된 셈 입니다. 그리고, 대학원 공부에서 가장 많이 요구되는 역량은 논리적 사고력 입니다. 대학원에서 연구를 수행하는데 핵심역량입니다. 독서량이 많으면 유리하고 글을 잘쓰는데 관심이 있다면 아주 좋습니다. 내가 한 일을 다른 사람에게 말로 잘 전달하는 능력도 의사소통 능력에 들어갑니다. 컴퓨터 언어 관련해서는 분석 툴(tool) 다루는 것을 두려워 하지 않는 태도가 필요합니다(분석 툴에는 SPSS, R 등 프로그램 활용이 포함 됨). 많은 학생들이 통계가 힘들다고 이야기 하는데, 제가 보기에는 한 번도 안 해본 프로그램을 사용하는 것에 대하여 지나치게 큰 장벽을 상상하고 겁을 내는 것 같습니다. \
> 대헉원 진학 후에는 지식습득 능력 외 측면이 학생의 성과에 지대한 영향을 줍니다. 저는 제 학생이 (A) 체력 단련 습관, (B) 성장 마인드셋, (C) 불확실한 상황에서 불안을 다스리는 건강한 방법을 갖고있으면 좋겠습니다. 

\

#### 2. 심리측정통계 대학원 졸업 후 어떤 진로가 있나요?

> 심리측정통계나 계량심리학 석사졸업 후 많은 경우에 조사 분야나 데이터수집 및 관리 분야, 혹은 정부출연 연구소로 진출합니다. 제가 석사공부를 시작할 때 까지만 해도 외국계 기업에만 일자리가 있었는데, 현재는 국내 기업에서도 다양한 분야에서의 데이터분석 전문가를 채용하고 있고, 기업에서 인사/평가 관련하여 자료분석을 담당하는 측정학자 인력 수요도 꾸준히 늘고있습니다. 정부출연연구소의 경우, 패널조사 수집과 관리에 있어서 심리측정학자를 필요로하는 직무가 있습니다. 박사졸업 후에는 연구실적을 쌓아서 학계에서 활동할 수 있습니다. 

\


<!-- #### 3 . 심리측정통계 연구실에서는 어떤 내용을 배우게 되나요?  -->
<!-- >  -->

<!-- \ -->

<!-- #### 4 . 학부 전공이 심리학이 아닌데 괜찮나요?   -->
<!-- > 심리학과 학부 학위가 필수는 아닙니다.  -->

<!-- \ -->

<!-- #### 5 . 어떤 과목을 수강하는 것이 진학에 유리할까요? -->

<!-- > '심리통계나 연구방법론 외에 심리측정통계 대학원 진학을 위해서 수강해야하는 과목이 있는지?'에 대해서는 심리학과에서 매년 개설되고 있는 '심리측정및실습' 과 '응용심리통계' 과목을 추천합니다. '수학과나 통계학과 과목을 미리 듣거나 이중전공을 해야 하는지?'에 대해서는 저는 기본적으로 통계를 적용할 수 있는 세부전공(임상이나 상담, 발달 등) 혹은 각자 전공분야 과목을 충실히 학습하는 것을 더 추천합니다. 심리측정, 계량심리를 비롯한 행동과학 연구방법론은 지극히 실용적인 목적에서 생긴 전공입니다. 방법론은 홀로 따로 존재하는 것이 아니라 세부 전공분야 맥락 속에서 필요에의해 생긴 것 이므로 방법론이 아닌 내용 측면 전공에도 관심이 있는 것이 좋습니다. 제 학생에게도 주전공(심리측정통계) 이외에 관심가는 세부 전공분야를 정하여 부전공 처럼 생각하고 공부하라고 권합니다. -->

<!-- \ -->

<!-- #### 6 . 영어를 어느 정도 잘해야 되나요? -->

<!-- > 적어도 영어로된 글을 읽고 이해 할 수 있어야 합니다. 질 좋은 자료들이 영어로 되어있는 경우가 많기 때문입니다. 간혹 '영어로 논문을 쓸 수 없을 것 같아서 걱정이 된다'는 학생들이 있는데, 영어보다 훨씬 더 중요한 것은 모국어를 잘하는 것입니다. 한국어로 논문을 잘 쓸 수 있으면 영어논문 쓰기는 한글로 쓴 것을 번역 하면 되고, 한국어로 논문을 잘 쓰는 능력을 기르는 것에 비하면 약간의 노력만 들이면 됩니다. -->

<!-- \ -->

<!-- #### 7 . 통계학과 수업을 미리 들어야 하나요? R프로그래밍 수업을 미리 들어야 하나요? -->

<!-- > 도움이 될 수 있겠지만 필수는 아닙니다. 입학 후에 해도 됩니다. -->




<!-- 수학과 수업을 미리 들어야 하나요? -->
<!-- 예/아니로 둘 중 하나로 만 대답해야 한다면 '아니오'입니다. 물론 수리적 측면이 탄탄하면 도움이 되겠지만 당장 방법론을 연구하기 위해서 수학 자체에 대한 지식을 직접적으로 사용하게 된다고 보기는 어렵습니다. 제가 생각하기에 심리측정통계를 전공하기 위한 핵심역량은 논리적/체계적 사고 입니다. 논리적 사고능력이 수리적인 능력과 연관이 있을수도 있지만 수학과에서 하는 연구와는 많이 다릅니다. 수학과에서 하는 증명을 아무리 많이 할 줄 알아도 심리학 맥락에서의 방법론 연구를 바로 할 수는 없습니다. -->